server:
  proxy:
    hostport: 127.0.0.1:5432
  admin:
    hostport: 127.0.0.1:8000

nodes:
  master:
    hostport: 192.168.56.100:5432
    role: master
    metadata: {}
  replica1:
    hostport: 192.168.56.101:5432
    role: replica
    metadata: {}

credentials:
  username: postgres
  database: postgres
  password: password
  options:
  ssl:
    enable: false
    sslmode: disable

pool:
  capacity: 2

healthcheck:
  delay: 60
  query: select now();
